name: Dependency Updates

on:
  schedule:
    - cron: '0 9 * * 1'  # Run every Monday at 9:00 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
    
    - name: Update requirements.txt
      run: |
        # Extract requirements from setup.py to requirements.in
        grep "install_requires" setup.py | sed 's/.*\[\(.*\)\].*/\1/' | tr -d ' ' | tr ',' '\n' | sed 's/^"\(.*\)"$/\1/' > requirements.in
        
        # Compile updated requirements
        pip-compile --upgrade requirements.in -o requirements.txt
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update dependencies
        title: '[Automated] Update dependencies'
        body: |
          This PR updates dependencies to their latest compatible versions.
          
          This is an automated PR created by the dependency update workflow.
        branch: dependency-updates
        base: main
